-- OpenPortalKit R7 Dashboard + Analytics
-- PostgreSQL baseline schema for privacy-conscious analytics and cached dashboard summaries.

create table if not exists opk_analytics_events (
    id uuid primary key,
    site_id text not null,
    event_type text not null,
    path text not null,
    hashed_session_id text not null,
    occurred_at timestamptz not null,
    referrer text null,
    user_agent text null,
    anonymized_ip_address inet null,
    is_bot boolean not null default false,
    metadata_json jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    constraint ck_opk_analytics_events_metadata_object
        check (jsonb_typeof(metadata_json) = 'object'),
    constraint ck_opk_analytics_events_no_raw_session
        check (hashed_session_id <> '')
);

create index if not exists ix_opk_analytics_events_site_occurred
    on opk_analytics_events (site_id, occurred_at desc);

create index if not exists ix_opk_analytics_events_site_type_occurred
    on opk_analytics_events (site_id, event_type, occurred_at desc);

create index if not exists ix_opk_analytics_events_path_occurred
    on opk_analytics_events (path, occurred_at desc);

create index if not exists ix_opk_analytics_events_bot_occurred
    on opk_analytics_events (is_bot, occurred_at desc);

create table if not exists opk_dashboard_snapshots (
    id uuid primary key,
    generated_at timestamptz not null,
    created_at timestamptz not null,
    expires_at timestamptz not null,
    source_checksum text not null,
    summary_json jsonb not null,
    source_modules_json jsonb not null default '[]'::jsonb,
    card_count integer not null default 0,
    alert_count integer not null default 0,
    actionable_alert_count integer not null default 0,
    schema_version integer not null default 1,
    constraint ck_opk_dashboard_snapshots_summary_object
        check (jsonb_typeof(summary_json) = 'object'),
    constraint ck_opk_dashboard_snapshots_source_modules_array
        check (jsonb_typeof(source_modules_json) = 'array'),
    constraint ck_opk_dashboard_snapshots_expiry
        check (expires_at > created_at),
    constraint ck_opk_dashboard_snapshots_counts
        check (
            card_count >= 0
            and alert_count >= 0
            and actionable_alert_count >= 0
        )
);

create index if not exists ix_opk_dashboard_snapshots_created
    on opk_dashboard_snapshots (created_at desc);

create index if not exists ix_opk_dashboard_snapshots_expires
    on opk_dashboard_snapshots (expires_at desc);

create index if not exists ix_opk_dashboard_snapshots_checksum
    on opk_dashboard_snapshots (source_checksum);

comment on table opk_analytics_events is
    'Privacy-conscious first-party analytics events. Raw session identifiers and raw IP addresses are not stored.';

comment on column opk_analytics_events.hashed_session_id is
    'Salted session hash generated by application code; raw session id is never persisted.';

comment on column opk_analytics_events.anonymized_ip_address is
    'Anonymized IP address only; IPv4 host byte and IPv6 lower 64 bits are removed before persistence.';

comment on table opk_dashboard_snapshots is
    'Cached dashboard summary snapshots used to keep admin dashboard reads off public request paths.';
